#!/bin/bash

## set up the backup date
NOW_DATE="date +%F"
NOW_DATE=$(eval "$BACKUP_DATE")
BACKUP_FOLDER=/home/leet/sql-wordpress
HISTORY=5
PASSWORD="TACOBELLBABAIESSSSSSSSSSSSS"

#mysql and wordpress backup
mysqldump -u leet -p$PASSWORD wordpress > "$BACKUP_FOLDER/DUMP$NOW_DATE.sql"
cp -R /var/www/wordpress "$BACKUP_FOLDER/wordpress$NOW_DATE"
chown -R leet:leet $BACKUP_FOLDER
chmod -R 700 $BACKUP_FOLDER

#clear out old stuff and keep 4 most new files
cd $BACKUP_FOLDER

ls -t | tail -n +$HISTORY | xargs rm -R --
